pipeline {
    agent any
    environment {
        REMOTE_USER = 'ubuntu'
        REMOTE_SERVER_IP = credentials("deployServerIP")
        BUILD_DIR = 'frontend'
    }

    stages {
        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm ci'
                }
            }
        }

        stage('Build') {
            steps {
                dir('frontend') {
                    sh 'npm run build'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                sshagent(credentials: ['remote-server']) {
                    sh "rsync -avz ./dist/ ${REMOTE_USER}@${REMOTE_SERVER_IP}:/var/www/core"
                }
            }
        }
    }

    post { 
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed'
        }
    }
}
